Prepush

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,9 +1,4 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-if branch=$(git symbolic-ref --short HEAD 2>/dev/null); then
-  echo "Current branch: $branch"
-else
-  echo "Not currently on a branch"
-fi
-if [ "master" = "master" ] || [ "master" = "dev" ]; then echo "Error: Cannot push to master or dev branch" && exit 1; fi
+if [ $(git symbolic-ref --short HEAD) = "master" ] || [ $(git symbolic-ref --short HEAD) = "dev" ]; then echo "Error: Cannot push to master or dev branch" && exit 1; fi
